# Generated by Django 4.1.1 on 2022-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_listproject_projectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdescription',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
